### ISSUE TITLE
Unable to use RS LED D2 in flow as actuator

### ISSUE THREAD

**Issue by JohanvanZanten** [TedTolboom/de.steinel#2]
Hi Ted,

You may have read the Athom Forum where I wrote that I bought a Steinel Floodlight but I recently bought a D2 as well as a replacement of a regular lamp. I installed the 0.02 version of the app but ran into issues when I wanted to use the lamp to be switched on by a different Sensor (a NeoCam MultiSensor). As I dragged the D2 card to the then area it wouldn't stick.

if you want me to test the app please let me know

**Comment by TedTolboom** [comment]
Hi Johan,

Can you indicate which card this is related to?
the D2 only uses the default onoff flow action cards... onoff capability has been registered in the device driver; are you able to switch on and off the D2 via Homey?
Can you share a screenshot of the flow?

You should also be able to control the D2 directly from the Neo sensor (without flow); by setting up a direct association (group 2 of the Neo) to the D2. But since the Neo does not support secure communication, this will only work if the D2 is also added non-secure (not sure if this is default)...

**Comment by JohanvanZanten** [comment]
Hi Ted,

I only tested (sofar) with the RS LED D2, I can manually switch off and on the D2 with homey
This is a video capture of the flow  and how the floweditor reacts:

Thnx in advance ;)

Btw this is already the latest version 0.0.3

**Comment by TedTolboom** [comment]
Hi Johan,

I can't see the video in your comment... can you upload it or add a link to e.g. dropbox from the GitHub site itself?

**Comment by JohanvanZanten** [comment]
Here you go: https://www.dropbox.com/s/2rcf3dfkeq76cfd/RS%20LED%20D2%20Flow.mp4?dl=0

**Comment by JohanvanZanten** [comment]
[RS LED D2 Flow.zip](https://github.com/TedTolboom/de.steinel/files/1649833/RS.LED.D2.Flow.zip)

**Comment by TedTolboom** [comment]
Strange... onoff capability is added in device manifest and registered in device driver...

Can you check if a reboot of Homey resolves this issue?
Otherwise, try to remove the device and re-include it..

**Comment by JohanvanZanten** [comment]
Already tried that multiple times; as when pairing to homey the best thing is to keepit need the device (so I unplug it from its usual location and plug it in near the device) and I was preliminary using the standard Z-Wave driver which is able to be used in a (very easy) flow like that (so I removed the steinel app and readded it)

grtx Johan

**Comment by TedTolboom** [comment]
@JohanvanZanten I cannot find what is causing this issue; will check with the other Z-wave developers.
Just to verify; the onoff flow action card for the floodlight is working correctly; right?

**Comment by TedTolboom** [comment]
Ah... damn... 
Yes, this is originating from the device class used: sensor. 
Which does not have the default onoff action and trigger cards; a limitation of Homey....

I think I will change it to light class, so that the onoff and dim cards will be available.
But then I will need to add the motion and illumination trigger cards myself....

**Comment by JohanvanZanten** [comment]
Currently using the floodlight with the standard Z-wave “driver” in other words: haven’t recreated the device yet

**Comment by TedTolboom** [comment]
Don’t try; will not work...
Need to make the modifications as indicated below...

**Comment by TedTolboom** [comment]
@JohanvanZanten is fixed in the current version that will be released to the app store
